### ISSUE TITLE
cisuseraccount ids incorrect

### ISSUE THREAD

**Issue by robertgendler** [mvdbent/CIS-macOS-Security#1]
The IDs for all the files in cisuseraccount have the incorrect ID. They do not match the filename. Thus when generate_baseline is ran, a baseline is generated in `build/baseline` with the incorrect list of files.

>  section: "useraccounts"
    rules:
      - useraccounts_disable_autorun_files_safari
      - useraccounts_enable_filename_extensions
      - useraccounts_guest_access_smb_disable
      - useraccounts_guest_account_disable
      - useraccounts_loginwindow_prompt_username_password_enforce
      - useraccounts_password_hints_disable
      - useraccounts_remove_guest_homefolder

**Comment by mvdbent** [comment]
thanks, both!
